
image:
  file: .gitpod.Dockerfile
tasks:
  - init: pip install --upgrade pip && pip install -r ./requirements.txt
vscode:
  extensions:
    - ms-python.python
    - ms-azuretools.vscode-docker
    - ikuyadeu.r
